### ISSUE TITLE
Cant use commands

### ISSUE THREAD

**Issue by PHV08** [saiteja-madha/discord-js-bot#382]
I'm running the code on visual studio code and the bot is online but i can't use commands idk why its showing error in logs this is what it shows when I use commands.
[2023-07-09 06:07:32] ERROR: Client Error: E11000 duplicate key error collection: myFirstDatabase.guilds index: id_1 dup key: { id: null }
[2023-07-09 06:07:56] ERROR: interactionRun: E11000 duplicate key error collection: myFirstDatabase.guilds index: id_1 dup key: { id: null }
[2023-07-09 06:07:56] ERROR: Client Error: E11000 duplicate key error collection: myFirstDatabase.guilds index: id_1 dup key: { id: null }

**Comment by a3ryk** [comment]
The error clearly says that there's a duplicate key with the same id

**Comment by PHV08** [comment]
what id?

**Comment by iamvikshan** [comment]
Maybe i am late lol, but It is a problem related to a duplicate key in a MongoDB collection. Specifically, it's related to a collection named `guilds` and an index named `id_1`. This error is raised because MongoDB enforces the uniqueness of values in indexed fields, and it has detected a duplicate key value for the `id` field in the `guilds` collection. 

To resolve this issue, you should investigate the data in the `guilds` collection to find the documents with a `null` value in the `id` field and decide how to handle them. You can either remove the duplicate documents, update them with a unique `id` value, or modify the index or schema to allow for non-unique values in the `id` field if that's acceptable for your use case. Make sure that your code and data insertion processes are not inadvertently creating duplicate keys in the collection.

to do the deletion you can use the CI or log in to your Atlas MongoDB dashboard and delete em.
